import { defineMessages } from 'react-intl';

export const commonLabel = defineMessages({
    videos: 'Videos',
    articles: 'Articles',
    games: 'Games',
    quiz: 'Quiz',
    lesson: 'lesson',

    welcomeUser: 'Welcome, {user}',
});

export const commonButton = defineMessages({
    login: 'Login',
});
export const commonMessage = defineMessages({
    home: 'Home',
    admins: 'Administrators',
    adminsLeader: 'Admins Leader',
    news: 'News',
    back: 'Back',
    category: 'Category',
    newsCategory: 'Course List',
    previewFailed: 'Preview failed',
    title: 'Title',
    status: 'Status',
    username: 'Username',
    fullName: 'Full Name',
    phone: 'Phone Number',
    group: 'Group',
    createdDate: 'Start Date',
    endDate: 'End Date',
    modifiedDate: 'Modified Date',
    userAdmin: 'Administrator',
    userAdminLeader: 'Admins Leader',
    profile: 'Profile',
    avatar: 'Avatar',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    validatePassword: 'Password must be at least 6 characters',
    confirmPassword: 'Confirm Password',
    passwordNotMatch: 'Passwords do not match',
    password: 'Password',
    userType: 'Who are you?',
    login: 'Login',
    logout: 'Logout',
    email: 'Email',
    name: 'Course Name',
    firstName: 'First Name',
    lastName: 'Last Name',
    gender: 'Gender',
    female: 'Female',
    male: 'Male',
    description: 'Description',
    groupPermission: 'Group Permission',
    listSetting: 'Settings',
    settingValue: 'Value',
    groupName: 'Group Name',
    isEditable: 'Is Editable',
    isSystem: 'Is System',
    settingKey: 'Setting Key',
    address: 'Address',
    ward: 'Ward/Commune',
    district: 'District',
    province: 'Province/City',
    nation: 'Nation',
    revenuee: 'Revenue',
    percent: 'Percent (%)',
    price: 'Price',
    date: 'Date',
    receiver: 'Receiver',
    changePassword: 'Change Password',
    forgetPassword: 'Forgot Password',
    register: 'Register',
    placeholderPassword: 'At least 6 characters',
    placeholderPhone: 'Enter your phone number',
    contactInfo: 'Contact Information',
    require: 'Required',
    note: 'Note',
    option: 'Option',
    checkout: 'Checkout',
    paymentDetail: 'Payment Details',
    totalPrice: 'Total Price',
    totalPriceService: 'Total price service',
    chooseOtherTime: 'Choose Another Time',
    paymentMethod: 'Payment Method',
    minute: 'Minute',
    allTime: 'Total Time',
    orderHistory: 'Order History',
    save: 'Save',
    changeLanguage: 'Change Language',
    book: 'Book',
    all: 'All',
    payment: 'Payment',
    addService: 'Add Service',
    update: 'Update',
    cancel: 'Cancel',
    edit: 'Edit',
    success: 'Success',
    fail: 'Fail',
    min: 'min',
    hour: 'hour',
    hours: 'hours',
    orderCode: 'Order Code',
    totalMoney: 'Total Money',
    time: 'Time',
    serviceName: 'Service Name',
    cash: 'Cash',
    card: 'Card',
    myCart: 'My Cart',
    myOrder: 'My Order',
    disc: 'Disc',
    actions: 'Actions',
    cancelSuccess: 'Cancel Order Success',
    cancelFail: 'Cancel Order Fail',
    cancelOrder: 'Cancel Order',
    confirmCancelOrder: 'Are you sure you want to cancel this order?',
    detailService: 'Detail Service',
    chooseEmployee: 'Chose Employee',
    confirm: 'Confirm',
    restriction: 'Restriction',
    goodToKnow: 'Good To Know',
    nodata: 'Unfortunately, there is no detail or evaluation of this service available.',
    from: 'From',
    detailColection: 'Detail Collection',
    colection: 'Collection',
    yourCartEmpty: 'Your cart is empty',
    ordersInCart: 'orders in cart',
    bookService: 'Book service',
    shortDescription: 'You have not added anything to your cart. Please add a new service to your cart.',
    order: 'Order',
    createRatingSuccess: 'Create rating success',
    createRatingFail: 'Create rating fail',
    getRatingFail: 'Get rating fail',
    paymentSuccess: 'Thank you, your order has been placed successfully',
    paymentFail: 'An error occurred, your order has not been processed',
    review: 'Review',
    rating: 'Rating',
    minutesAgo: 'minutes ago',
    ago: 'ago',
    second: 'second',
    day: 'day',
    week: 'week',
    month: 'month',
    year: 'year',
    TODAY: 'TODAY',
    YESTERDAY: 'YESTERDAY',
    LASTWEEK: 'LAST WEEK',
    LASTMONTH: 'LAST MONTH',
    introduction: 'Introduction store',
    timeWork: 'Time Work',
    location: 'Location/Map',
    descriptionWork: 'Our work on nails',
    cancelService: 'Cancel service',
    saveMoney: 'Save',
    collapse: 'Collapse',
    seeMore: 'See more',
    orderFail: 'Order Fail',
    orderNumber: 'Your order number is',
    wait: 'wait',
    getInvoiceFail: 'Get invoice details failed',
    invalidPhone: 'Invalid phone number, please re-enter',
    invalidEmail: 'Invalid email, please re-enter',
    deleteService: 'Are you sure you want to delete this service?',
    minUtil: 'm',
    hourUtil: 'h',
    rebook: 'Rebook',
    waiting: 'Waiting',
    completed: 'Completed',
    canceled: 'Canceled',
    rebookSuccess: 'Rebook Success',
    rebookFail: 'rebookFail',
    taxLabel: 'Tax',
});

export const dayOfWeek = defineMessages({
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
});
